#START
#CNM module angular scan run in May 16.(Program 14)
Run=RUN
inputFile=AnalysisTree/AnalysisTree_RUN.root
outputFile=TYPE_Output_RUN.root
fei4Z=724
readAlignmentFromfile=RALFF
doTelescopeMatching=1
doChannelMasking_=0
channelMaskFile=chmask.txt
residualSigmaDUT=0.026
nStrips=254
pitchDUT=0.09
#only needed by Alignment Analysis
isProductionmode=1
alignmentOutputFile=alignmentparOutput_may16_Prog14.txt
#END
